export type ParameterType = 'string' | 'number' | 'boolean' | 'array:string' | 'array:number';

export interface EndpointParameter {
  name: string;
  in: 'path' | 'query';
  required: boolean;
  type: ParameterType;
}

export interface EndpointDefinition {
  path: string;
  method: 'GET';
  toolName: string;
  summary: string;
  pathParams: EndpointParameter[];
  queryParams: EndpointParameter[];
}

export const ENDPOINTS: EndpointDefinition[] = [
  { path: '/api/Location/Browse/{locationType}/{locationName}', method: 'GET', toolName: 'ukp_location_browse', summary: 'Returns a list of locations, both parent and child', pathParams: [{ name: 'locationType', in: 'path', required: true, type: 'number' }, { name: 'locationName', in: 'path', required: true, type: 'string' }], queryParams: [] },
  { path: '/api/Location/Constituency/Search', method: 'GET', toolName: 'ukp_location_constituency_search', summary: 'Returns a list of constituencies', pathParams: [], queryParams: [{ name: 'searchText', in: 'query', required: false, type: 'string' }, { name: 'skip', in: 'query', required: false, type: 'number' }, { name: 'take', in: 'query', required: false, type: 'number' }] },
  { path: '/api/Location/Constituency/{id}', method: 'GET', toolName: 'ukp_location_constituency', summary: 'Returns a constituency by ID', pathParams: [{ name: 'id', in: 'path', required: true, type: 'number' }], queryParams: [] },
  { path: '/api/Location/Constituency/{id}/Synopsis', method: 'GET', toolName: 'ukp_location_constituency_synopsis', summary: 'Returns a synopsis by constituency ID', pathParams: [{ name: 'id', in: 'path', required: true, type: 'number' }], queryParams: [] },
  { path: '/api/Location/Constituency/{id}/Representations', method: 'GET', toolName: 'ukp_location_constituency_representations', summary: 'Returns a list of representations by constituency ID', pathParams: [{ name: 'id', in: 'path', required: true, type: 'number' }], queryParams: [] },
  { path: '/api/Location/Constituency/{id}/Geometry', method: 'GET', toolName: 'ukp_location_constituency_geometry', summary: 'Returns geometry by constituency ID', pathParams: [{ name: 'id', in: 'path', required: true, type: 'number' }], queryParams: [] },
  { path: '/api/Location/Constituency/{id}/ElectionResults', method: 'GET', toolName: 'ukp_location_constituency_election_results', summary: 'Returns a list of election results by constituency ID', pathParams: [{ name: 'id', in: 'path', required: true, type: 'number' }], queryParams: [] },
  { path: '/api/Location/Constituency/{id}/ElectionResult/{electionId}', method: 'GET', toolName: 'ukp_location_constituency_election_result', summary: 'Returns an election result by constituency and election id', pathParams: [{ name: 'id', in: 'path', required: true, type: 'number' }, { name: 'electionId', in: 'path', required: true, type: 'number' }], queryParams: [] },
  { path: '/api/Location/Constituency/{id}/ElectionResult/Latest', method: 'GET', toolName: 'ukp_location_constituency_election_result_latest', summary: 'Returns latest election result by constituency id', pathParams: [{ name: 'id', in: 'path', required: true, type: 'number' }], queryParams: [] },
  { path: '/api/LordsInterests/Register', method: 'GET', toolName: 'ukp_lords_interests_register', summary: 'Returns a list of registered interests', pathParams: [], queryParams: [{ name: 'searchTerm', in: 'query', required: false, type: 'string' }, { name: 'page', in: 'query', required: false, type: 'number' }, { name: 'includeDeleted', in: 'query', required: false, type: 'boolean' }] },
  { path: '/api/LordsInterests/Staff', method: 'GET', toolName: 'ukp_lords_interests_staff', summary: 'Returns a list of staff', pathParams: [], queryParams: [{ name: 'searchTerm', in: 'query', required: false, type: 'string' }, { name: 'page', in: 'query', required: false, type: 'number' }] },
  { path: '/api/Members/Search', method: 'GET', toolName: 'ukp_members_search', summary: 'Returns a list of current members of the Commons or Lords', pathParams: [], queryParams: [{ name: 'Name', in: 'query', required: false, type: 'string' }, { name: 'Location', in: 'query', required: false, type: 'string' }, { name: 'PostTitle', in: 'query', required: false, type: 'string' }, { name: 'PartyId', in: 'query', required: false, type: 'number' }, { name: 'House', in: 'query', required: false, type: 'number' }, { name: 'ConstituencyId', in: 'query', required: false, type: 'number' }, { name: 'NameStartsWith', in: 'query', required: false, type: 'string' }, { name: 'Gender', in: 'query', required: false, type: 'string' }, { name: 'MembershipStartedSince', in: 'query', required: false, type: 'string' }, { name: 'MembershipEnded.MembershipEndedSince', in: 'query', required: false, type: 'string' }, { name: 'MembershipEnded.MembershipEndReasonIds', in: 'query', required: false, type: 'array:number' }, { name: 'MembershipInDateRange.WasMemberOnOrAfter', in: 'query', required: false, type: 'string' }, { name: 'MembershipInDateRange.WasMemberOnOrBefore', in: 'query', required: false, type: 'string' }, { name: 'MembershipInDateRange.WasMemberOfHouse', in: 'query', required: false, type: 'number' }, { name: 'IsEligible', in: 'query', required: false, type: 'boolean' }, { name: 'IsCurrentMember', in: 'query', required: false, type: 'boolean' }, { name: 'PolicyInterestId', in: 'query', required: false, type: 'number' }, { name: 'Experience', in: 'query', required: false, type: 'string' }, { name: 'skip', in: 'query', required: false, type: 'number' }, { name: 'take', in: 'query', required: false, type: 'number' }] },
  { path: '/api/Members/SearchHistorical', method: 'GET', toolName: 'ukp_members_search_historical', summary: 'Returns a list of members of the Commons or Lords', pathParams: [], queryParams: [{ name: 'name', in: 'query', required: false, type: 'string' }, { name: 'dateToSearchFor', in: 'query', required: false, type: 'string' }, { name: 'skip', in: 'query', required: false, type: 'number' }, { name: 'take', in: 'query', required: false, type: 'number' }] },
  { path: '/api/Members/{id}', method: 'GET', toolName: 'ukp_members_get_by_id', summary: 'Return member by ID', pathParams: [{ name: 'id', in: 'path', required: true, type: 'number' }], queryParams: [{ name: 'detailsForDate', in: 'query', required: false, type: 'string' }] },
  { path: '/api/Members/{id}/Biography', method: 'GET', toolName: 'ukp_members_biography', summary: 'Return biography of member by ID', pathParams: [{ name: 'id', in: 'path', required: true, type: 'number' }], queryParams: [] },
  { path: '/api/Members/{id}/Contact', method: 'GET', toolName: 'ukp_members_contact', summary: 'Return list of contact details of member by ID', pathParams: [{ name: 'id', in: 'path', required: true, type: 'number' }], queryParams: [] },
  { path: '/api/Members/{id}/ContributionSummary', method: 'GET', toolName: 'ukp_members_contribution_summary', summary: 'Return contribution summary of member by ID', pathParams: [{ name: 'id', in: 'path', required: true, type: 'number' }], queryParams: [{ name: 'page', in: 'query', required: false, type: 'number' }] },
  { path: '/api/Members/{id}/Edms', method: 'GET', toolName: 'ukp_members_edms', summary: 'Return list of early day motions of member by ID', pathParams: [{ name: 'id', in: 'path', required: true, type: 'number' }], queryParams: [{ name: 'page', in: 'query', required: false, type: 'number' }] },
  { path: '/api/Members/{id}/Experience', method: 'GET', toolName: 'ukp_members_experience', summary: 'Return experience of member by ID', pathParams: [{ name: 'id', in: 'path', required: true, type: 'number' }], queryParams: [] },
  { path: '/api/Members/{id}/Focus', method: 'GET', toolName: 'ukp_members_focus', summary: 'Return list of areas of focus of member by ID', pathParams: [{ name: 'id', in: 'path', required: true, type: 'number' }], queryParams: [] },
  { path: '/api/Members/History', method: 'GET', toolName: 'ukp_members_history', summary: 'Return members by ID with list of their historical names, parties and memberships', pathParams: [], queryParams: [{ name: 'ids', in: 'query', required: false, type: 'array:number' }] },
  { path: '/api/Members/{id}/LatestElectionResult', method: 'GET', toolName: 'ukp_members_latest_election_result', summary: 'Return latest election result of member by ID', pathParams: [{ name: 'id', in: 'path', required: true, type: 'number' }], queryParams: [] },
  { path: '/api/Members/{id}/Portrait', method: 'GET', toolName: 'ukp_members_portrait', summary: 'Return portrait of member by ID', pathParams: [{ name: 'id', in: 'path', required: true, type: 'number' }], queryParams: [{ name: 'cropType', in: 'query', required: false, type: 'number' }, { name: 'webVersion', in: 'query', required: false, type: 'boolean' }] },
  { path: '/api/Members/{id}/PortraitUrl', method: 'GET', toolName: 'ukp_members_portrait_url', summary: 'Return portrait url of member by ID', pathParams: [{ name: 'id', in: 'path', required: true, type: 'number' }], queryParams: [] },
  { path: '/api/Members/{id}/RegisteredInterests', method: 'GET', toolName: 'ukp_members_registered_interests', summary: 'Return list of registered interests of member by ID', pathParams: [{ name: 'id', in: 'path', required: true, type: 'number' }], queryParams: [{ name: 'house', in: 'query', required: false, type: 'number' }] },
  { path: '/api/Members/{id}/Staff', method: 'GET', toolName: 'ukp_members_staff', summary: 'Return list of staff of member by ID', pathParams: [{ name: 'id', in: 'path', required: true, type: 'number' }], queryParams: [] },
  { path: '/api/Members/{id}/Synopsis', method: 'GET', toolName: 'ukp_members_synopsis', summary: 'Return synopsis of member by ID', pathParams: [{ name: 'id', in: 'path', required: true, type: 'number' }], queryParams: [] },
  { path: '/api/Members/{id}/Thumbnail', method: 'GET', toolName: 'ukp_members_thumbnail', summary: 'Return thumbnail of member by ID', pathParams: [{ name: 'id', in: 'path', required: true, type: 'number' }], queryParams: [] },
  { path: '/api/Members/{id}/ThumbnailUrl', method: 'GET', toolName: 'ukp_members_thumbnail_url', summary: 'Return thumbnail url of member by ID', pathParams: [{ name: 'id', in: 'path', required: true, type: 'number' }], queryParams: [] },
  { path: '/api/Members/{id}/Voting', method: 'GET', toolName: 'ukp_members_voting', summary: 'Return list of votes by member by ID', pathParams: [{ name: 'id', in: 'path', required: true, type: 'number' }], queryParams: [{ name: 'house', in: 'query', required: true, type: 'number' }, { name: 'page', in: 'query', required: false, type: 'number' }] },
  { path: '/api/Members/{id}/WrittenQuestions', method: 'GET', toolName: 'ukp_members_written_questions', summary: 'Return list of written questions by member by ID', pathParams: [{ name: 'id', in: 'path', required: true, type: 'number' }], queryParams: [{ name: 'page', in: 'query', required: false, type: 'number' }] },
  { path: '/api/Parties/StateOfTheParties/{house}/{forDate}', method: 'GET', toolName: 'ukp_parties_state_of_the_parties', summary: 'Returns current state of parties', pathParams: [{ name: 'house', in: 'path', required: true, type: 'number' }, { name: 'forDate', in: 'path', required: true, type: 'string' }], queryParams: [] },
  { path: '/api/Parties/LordsByType/{forDate}', method: 'GET', toolName: 'ukp_parties_lords_by_type', summary: 'Returns the composition of the House of Lords by peerage type.', pathParams: [{ name: 'forDate', in: 'path', required: true, type: 'string' }], queryParams: [] },
  { path: '/api/Parties/GetActive/{house}', method: 'GET', toolName: 'ukp_parties_get_active', summary: 'Returns a list of current parties with at least one active member.', pathParams: [{ name: 'house', in: 'path', required: true, type: 'number' }], queryParams: [] },
  { path: '/api/Posts/GovernmentPosts', method: 'GET', toolName: 'ukp_posts_government_posts', summary: 'Returns a list of government posts.', pathParams: [], queryParams: [{ name: 'departmentId', in: 'query', required: false, type: 'number' }] },
  { path: '/api/Posts/OppositionPosts', method: 'GET', toolName: 'ukp_posts_opposition_posts', summary: 'Returns a list of opposition posts.', pathParams: [], queryParams: [{ name: 'departmentId', in: 'query', required: false, type: 'number' }] },
  { path: '/api/Posts/Spokespersons', method: 'GET', toolName: 'ukp_posts_spokespersons', summary: 'Returns a list of spokespersons.', pathParams: [], queryParams: [{ name: 'partyId', in: 'query', required: false, type: 'number' }] },
  { path: '/api/Posts/Departments/{type}', method: 'GET', toolName: 'ukp_posts_departments', summary: 'Returns a list of departments.', pathParams: [{ name: 'type', in: 'path', required: true, type: 'number' }], queryParams: [] },
  { path: '/api/Posts/SpeakerAndDeputies/{forDate}', method: 'GET', toolName: 'ukp_posts_speaker_and_deputies', summary: 'Returns a list containing the speaker and deputy speakers.', pathParams: [{ name: 'forDate', in: 'path', required: true, type: 'string' }], queryParams: [] },
  { path: '/api/Reference/PolicyInterests', method: 'GET', toolName: 'ukp_reference_policy_interests', summary: 'Returns a list of policy interest.', pathParams: [], queryParams: [] },
  { path: '/api/Reference/Departments', method: 'GET', toolName: 'ukp_reference_departments', summary: 'Returns a list of departments.', pathParams: [], queryParams: [{ name: 'id', in: 'query', required: false, type: 'number' }, { name: 'nameContains', in: 'query', required: false, type: 'string' }] },
  { path: '/api/Reference/AnsweringBodies', method: 'GET', toolName: 'ukp_reference_answering_bodies', summary: 'Returns a list of answering bodies.', pathParams: [], queryParams: [{ name: 'id', in: 'query', required: false, type: 'number' }, { name: 'nameContains', in: 'query', required: false, type: 'string' }] },
  { path: '/api/Reference/Departments/{id}/Logo', method: 'GET', toolName: 'ukp_reference_departments_logo', summary: 'Returns department logo.', pathParams: [{ name: 'id', in: 'path', required: true, type: 'number' }], queryParams: [] }
];

export const ENDPOINTS_BY_TOOL_NAME = new Map(ENDPOINTS.map((endpoint) => [endpoint.toolName, endpoint]));
